// src/app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// No AuthProvider here if it's in (main)/layout.tsx
// It's generally better to have AuthProvider wrap specific parts of the app
// that need auth, or at the highest level necessary. (main)/layout.tsx is a good spot.

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App', // This will be overridden by more specific metadata
   description: 'Generated by create next app',
};
export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
     <html lang="en">
       <body className={inter.className}>
         {/* AuthProvider could be here if Navbar is here and needs it,
             or if every single page needs auth context immediately.
             For this structure, (main)/layout.tsx is fine. */}
         {children}
       </body>
     </html>
   );
}
